import { chromium } from "playwright";
const SP = "/private/tmp/claude-501/-Users-lukaskellerstein-Projects-Github-lukaskellerstein-rex/ae66f044-4b97-4f9d-aac5-2b909733a7d7/scratchpad";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
await page.goto("file://" + SP + "/rex-shell-redesign.html");
await page.waitForTimeout(6000);
await page.screenshot({ path: SP + "/screens-page.png" });
const boxes = await page.$$eval("iframe", (els) => els.map((e) => { const b = e.getBoundingClientRect(); return { x: Math.round(b.x), y: Math.round(b.y), w: Math.round(b.width), h: Math.round(b.height) }; }));
console.log(JSON.stringify(boxes));
await browser.close();
